### ISSUE TITLE
Fix index.html "modals"

### ISSUE THREAD

**Issue by JBallin** [Brechy/fam#16]
Clicking on the categories doesn't bring the pop-up with the description.

**Comment by Brechy** [comment]
I will need you to either provide instructions for reproducing the bug or wait for my PR request. I have not created one yet for these final changes. Right now everything works for me, so if I cannot reproduce this bug I can't fix it.

**Comment by Brechy** [comment]
Bug cannot be reproduced in current index.html fixes.

**Comment by JBallin** [comment]
agreed, #17 seems to fix
