### ISSUE TITLE
Fix format of Database

### ISSUE THREAD

**Issue by Brechy** [Brechy/fam#34]
Database looks janky, possibly because the bio is too long and it messing up the symmetry of the DB making it hard to read. 
![screen shot 2018-07-06 at 10 28 44 am](https://user-images.githubusercontent.com/24580640/42392358-68433fb6-8107-11e8-8b7c-fb5b6dd461fa.png)

**Comment by JBallin** [comment]
I think that this isn't something fixable. I added an `npm run db-dev` and `npm run db-prod` script in #67 that will only pull some of the fields, you can always do the same as needed (`select name, city, email from users`).
